"""empty message

Revision ID: 7a24ff32a0cc
Revises: None
Create Date: 2018-08-06 09:41:26.670807

"""

# revision identifiers, used by Alembic.
revision = '7a24ff32a0cc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=164), nullable=True),
    sa.Column('appendix', sa.String(length=164), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('upload_name', sa.Text(), nullable=True),
    sa.Column('present_name', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('article_url', sa.Text(), nullable=True),
    sa.Column('upload_url', sa.Text(), nullable=True),
    sa.Column('a_time', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=164), nullable=True),
    sa.Column('liked_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=164), nullable=True),
    sa.Column('email', sa.String(length=164), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=164), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('startups')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('photos')
    op.drop_table('notice')
    op.drop_table('movies')
    op.drop_table('courses')
    op.drop_table('articles')
    op.drop_table('animes')
    ### end Alembic commands ###
